name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: application.properties
      run: |
       cd ./src/main/resources
       touch ./application.properties
       echo "{{ secrets.DATA_SOURCE }}">> ./application.properties
      shell: bash
        
    - name: Build with Gradle Wrapper
      run: |
       chmod +x gradlew
       ./gradlew build

    - name: web docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:0.1 .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:0.1
