name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup MYSQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: ${{secrets.DB_PW}}
        mysql databese: 'mydb'

    - name: Application.properties
      run: |
       cd src/main
       mkdir resources
       cd resources
       touch application.properties
       echo "{{ secrets.DATA_SOURCE }}">> application.properties
       ls -l
       vi application.properties
      shell: bash
        
    - name: Build with Gradle Wrapper
      run: |
       chmod +x gradlew
       ./gradlew build

    - name: Docker image build and dockerhub push
      run: |
        docker build -t ${{ secrets.DOCKER_REPO }}:spring .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_REPO }}:spring

    - name: Ec2 docker-compose up
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ubuntu
        key: ${{secrets.KEYPAIR}}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker compose down
          docker rmi ${{ secrets.DOCKER_REPO }}:spring
          docker pull ${{ secrets.DOCKER_REPO }}:spring
          docker compose up -d
          docker logout
